In [ ]:
!pip install Twython
import pandas as pd
import numpy as np 
from twython import Twython

CONSUMER_KEY = "KbFtyE3UpWo0xdnQrEPm3fVAk"
CONSUMER_SECRET = "SzhJ73h83C9v9NgP0EZ4MAP9Hes9FEDbom3602zFTmeXIM3l60"
OAUTH_TOKEN = "1081482990340001792-SWbHXXm4OmahpLSGfsnQBI19rbf5cm"
OAUTH_TOKEN_SECRET = "Ftu6O9WfIUFPzmFyUMtCJUAhkkiPABWFRMG9HJqcLNEu5"
twitter = Twython(
    CONSUMER_KEY, CONSUMER_SECRET,
    OAUTH_TOKEN, OAUTH_TOKEN_SECRET)

Collecting Twython
  Downloading https://files.pythonhosted.org/packages/24/80/579b96dfaa9b536efde883d4f0df7ea2598a6f3117a6dd572787f4a2bcfb/twython-3.8.2-py3-none-any.whl
Requirement already satisfied: requests-oauthlib>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from Twython) (1.3.0)
Requirement already satisfied: requests>=2.1.0 in /usr/local/lib/python3.7/dist-packages (from Twython) (2.23.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from requests-oauthlib>=0.4.0->Twython) (3.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.1.0->Twython) (2021.5.30)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.1.0->Twython) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.1.0->Twython) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.1.0->Twython) (1.24.3)
Installing collected packages: Twython
Successfully installed Twython-3.8.2

In [ ]:
tweets = []
MAX_ATTEMPTS = 40
COUNT_OF_TWEETS_TO_BE_FETCHED = 1000

for i in range(0,MAX_ATTEMPTS):

    if(COUNT_OF_TWEETS_TO_BE_FETCHED < len(tweets)):
        print("We Got ", len(tweets), " tweets!!!")
        break # we got the  tweets... !!

    #----------------------------------------------------------------#
    # STEP 1: Query Twitter
    # STEP 2: Save the returned tweets
    # STEP 3: Get the next max_id
    #----------------------------------------------------------------#

    # STEP 1: Query Twitter
    if(0 == i):
        # Query twitter for data. 
        results = twitter.search(q="ηλεκτροκίνηση",count='100')
        print("I Got:", len(results['statuses']), " tweets")
    else:
        # After the first call we should have max_id from result of previous call. Pass it in query.
        results = twitter.search(q="ηλεκτροκίνηση",count='100', include_entities='true',max_id=next_max_id)
        print("I Got:", len(results['statuses']), " tweets")


    # STEP 2: Save the returned tweets
    for result in results['statuses']:
    #tweet_text = result['text']
        tweets.append(result)


    # STEP 3: Get the next max_id
    try:
        # Parse the data returned to get max_id to be passed in consequent call.
        next_results_url_params = results['search_metadata']['next_results']
        next_max_id = next_results_url_params.split('max_id=')[1].split('&')[0]
    except:
        # No more next pages
        break

I Got: 100  tweets
I Got: 100  tweets
I Got: 1  tweets
I Got: 0  tweets

In [ ]:
tweets_df = pd.DataFrame(tweets)

In [ ]:
tweets_df

                         created_at  ...  quoted_status
0    Sun Jul 04 10:23:40 +0000 2021  ...            NaN
1    Sat Jul 03 18:58:04 +0000 2021  ...            NaN
2    Sat Jul 03 18:55:21 +0000 2021  ...            NaN
3    Sat Jul 03 18:29:38 +0000 2021  ...            NaN
4    Sat Jul 03 13:55:38 +0000 2021  ...            NaN
..                              ...  ...            ...
196  Sun Jun 27 02:47:46 +0000 2021  ...            NaN
197  Sat Jun 26 16:30:54 +0000 2021  ...            NaN
198  Sat Jun 26 15:59:56 +0000 2021  ...            NaN
199  Sat Jun 26 13:30:05 +0000 2021  ...            NaN
200  Sat Jun 26 11:29:58 +0000 2021  ...            NaN

[201 rows x 30 columns]

In [ ]:
ShortTweets = tweets_df[['created_at','text','retweeted_status','retweet_count','favorite_count','retweeted']]
ShortTweets

                         created_at  ... retweeted
0    Sun Jul 04 10:23:40 +0000 2021  ...     False
1    Sat Jul 03 18:58:04 +0000 2021  ...     False
2    Sat Jul 03 18:55:21 +0000 2021  ...     False
3    Sat Jul 03 18:29:38 +0000 2021  ...     False
4    Sat Jul 03 13:55:38 +0000 2021  ...     False
..                              ...  ...       ...
196  Sun Jun 27 02:47:46 +0000 2021  ...     False
197  Sat Jun 26 16:30:54 +0000 2021  ...     False
198  Sat Jun 26 15:59:56 +0000 2021  ...     False
199  Sat Jun 26 13:30:05 +0000 2021  ...     False
200  Sat Jun 26 11:29:58 +0000 2021  ...     False

[201 rows x 6 columns]

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
ShortTweets.to_excel("/content/gdrive/My Drive/Colab Notebooks/BD2021/Final Exercise/Twitter/EVtweets.xlsx")